services:
  - type: web
    name: todolist-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://your-frontend-domain.vercel.app
      - key: API_KEY
        value: 0ICVyrNhPL56Oss58qv-_y42PhSQvYcPm6Vz26j4bNw
